import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import Header from '@/components/header';
import { cn } from '@/lib/utils';
import './globals.css';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'bg-header-mobile md:bg-header-tablet xl:bg-header-desktop min-h-screen bg-contain bg-no-repeat font-sans antialiased',
          fontSans.variable,
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
